/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 182210051
 */
public class MenuPrincipal extends javax.swing.JFrame implements InternalFrameListener {

    /**
     * Creates new form MenuPrincipal
     *
     */
    
    private boolean flagGuiCadCliente = false;
    private boolean flagGuiManutencaoCliente = false;
    
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadCliente = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManuCliente = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");

        jmiCadCliente.setText("CadCliente");
        jmiCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadClienteActionPerformed(evt);
            }
        });
        jmiCadCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiCadClienteKeyPressed(evt);
            }
        });
        jmCadastro.add(jmiCadCliente);

        jMenuBar1.add(jmCadastro);

        jmManutencao.setText("Manutenção");
        jmManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManutencaoActionPerformed(evt);
            }
        });
        jmManutencao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmManutencaoKeyPressed(evt);
            }
        });

        jmiManuCliente.setText("ManuCliente");
        jmiManuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManuClienteActionPerformed(evt);
            }
        });
        jmiManuCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiManuClienteKeyPressed(evt);
            }
        });
        jmManutencao.add(jmiManuCliente);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      private void abrirCadCliente(){
        if(!flagGuiCadCliente){
            GUICadCliente gcc = new GUICadCliente();
            jdpAreaDeTrabalho.add(gcc);
            gcc.setVisible(true);
            
            flagGuiCadCliente = true;
            gcc.addInternalFrameListener(this);
        }//fim do if
    }//fim do método abrirCadCliente
      
      private void abrirManuCliente(){
        if(!flagGuiManutencaoCliente){
            GUIManutencaoCliente gmc = new GUIManutencaoCliente();
            jdpAreaDeTrabalho.add(gmc);
            gmc.setVisible(true);
            
            flagGuiManutencaoCliente = true;
            gmc.addInternalFrameListener(this);
        }//fim do if
    }//fim do método abrirManuProduto )
    //Eventos
      
    private void jmiCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadClienteActionPerformed
        // TODO add your handling code here:
        abrirCadCliente();
    }//GEN-LAST:event_jmiCadClienteActionPerformed

    private void jmiCadClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiCadClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirCadCliente();
        }
    }//GEN-LAST:event_jmiCadClienteKeyPressed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        // TODO add your handling code here:
           System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiManuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManuClienteActionPerformed
        // TODO add your handling code here:
         abrirManuCliente();
    }//GEN-LAST:event_jmiManuClienteActionPerformed

    private void jmiManuClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiManuClienteKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirManuCliente();
        }
    }//GEN-LAST:event_jmiManuClienteKeyPressed

    private void jmManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManutencaoActionPerformed
        // TODO add your handling code here:
        abrirManuCliente();
    }//GEN-LAST:event_jmManutencaoActionPerformed

    private void jmManutencaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmManutencaoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirManuCliente();
        }
    }//GEN-LAST:event_jmManutencaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadCliente;
    private javax.swing.JMenuItem jmiManuCliente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
         //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
      //To change body of generated methods, choose Tools | Templates
       if (ife.getInternalFrame() instanceof GUICadCliente){
            flagGuiCadCliente = false;
       }else if (ife.getInternalFrame() instanceof GUIManutencaoCliente ){
            flagGuiManutencaoCliente = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
       //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
         //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
         //To change body of generated methods, choose Tools | Templates.
    }
}
